var settings = {
	text : [
		'Lorem ipsum dolor sit amet',
		'consectetur adipiscing elit',
		'Nullam adipiscing porta metus quis dignissim',
		' Etiam odio orci, aliquam ac pulvinar in, ullamcorper sed augue',
		'In ut justo non odio convallis ultrices',
		'Quisque quam nunc, elementum sit amet ultrices sed, consectetur in sem',
		'Nam vulputate pellentesque',
		'diam eget sagittis',
		'Sed id blandit leo',
		'Nam nec ipsum tincidunt, aliquam risus eu, tincidunt magna',
		'Cras egestas sagittis neque, a venenatis est aliquet ut',
		'Nam egestas viverra neque',
		'Lorem ipsum dolor sit amet',
		'consectetur adipiscing elit',
		'Nullam adipiscing porta metus quis dignissim',
		' Etiam odio orci, aliquam ac pulvinar in, ullamcorper sed augue',
		'In ut justo non odio convallis ultrices',
		'Quisque quam nunc, elementum sit amet ultrices sed, consectetur in sem',
		'Nam vulputate pellentesque',
		'diam eget sagittis',
		'Sed id blandit leo',
		'Nam nec ipsum tincidunt, aliquam risus eu, tincidunt magna',
		'Cras egestas sagittis neque, a venenatis est aliquet ut',
		'Nam egestas viverra neque',
		'Lorem ipsum dolor sit amet',
		'consectetur adipiscing elit',
		'Nullam adipiscing porta metus quis dignissim',
		' Etiam odio orci, aliquam ac pulvinar in, ullamcorper sed augue',
		'In ut justo non odio convallis ultrices',
		'Quisque quam nunc, elementum sit amet ultrices sed, consectetur in sem',
		'Nam vulputate pellentesque',
		'diam eget sagittis',
		'Sed id blandit leo',
		'Nam nec ipsum tincidunt, aliquam risus eu, tincidunt magna',
		'Cras egestas sagittis neque, a venenatis est aliquet ut',
		'Nam egestas viverra neque'
	]
};